#!/bin/bash

#SBATCH --nodes=1
#SBATCH --job-name=part-gtsm
#SBATCH --tasks-per-node=128
#SBATCH --time=0-01:00:00
#SBATCH --partition=genoa
#SBATCH --exclusive
##SBATCH --contiguous

module purge
module load 2022
module load intel/2022a

root=/home/mverlaan/einf220/fromDavid
export DFLOWFMDIR=$root/delft3dfm_2023.02/

cd ./stochModel/input_dflowfm/

mdu_file=gtsm_fine.mdu
n_part=20
submit_script=../bin/partition_snellius.sh

$submit_script $mdu_file $n_part